export const config = {
  OPERATOR_NUMBER: import.meta.env.VITE_WHATSAPP_OPERATOR_PHONE_NUMBER,
  OPERATOR_EMAIL: import.meta.env.VITE_COMPANY_EMAIL,
  SITE_URL: import.meta.env.VITE_COMPANY_SITE_URL,
  FACEBOOK_URL: import.meta.env.VITE_COMPANY_FACEBOOK_URL,
  INSTAGRAM_URL: import.meta.env.VITE_COMPANY_INSTAGRAM_URL,
}